name: Metadata

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@a2206170adbc21da4d40fb5e79c70165255c81ba # v1.31.0
