name: Metadata

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3
