name: Metadata

on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, edited, synchronize]

jobs:
  validate:
    name: Validate
    uses: defenseunicorns/uds-common/.github/workflows/commitlint.yaml@3a4908e410409ab908df7c1710ecca04c1647703 # v1.30.1
