name: Test

# This workflow is triggered on pull requests to the main branch.
on:
  pull_request:
    branches: [main]
    types: [milestoned, opened, synchronize]
    paths-ignore:
      - "**.md"
      - "**.jpg"
      - "**.png"
      - "**.gif"
      - "**.svg"
      - "adr/**"
      - "docs/**"
      - ".gitignore"
      - "renovate.json"
      - ".release-please-config.json"
      - "release-please-config.json"
      - "oscal-component.yaml"
      - "CODEOWNERS"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "SECURITY.md"

# Abort prior jobs in the same workflow / PR
concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  run-test:
    name: ${{ matrix.type }} ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    timeout-minutes: 20
    strategy:
      matrix:
        flavor: [upstream, registry1]
        type: [install, upgrade]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Environment setup
        uses: defenseunicorns/uds-common/.github/actions/setup@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3
        with:
          registry1Username: ${{ secrets.IRON_BANK_ROBOT_USERNAME }}
          registry1Password: ${{ secrets.IRON_BANK_ROBOT_PASSWORD }}
          ghToken: ${{ secrets.GITHUB_TOKEN }}

      - name: Test
        uses: defenseunicorns/uds-common/.github/actions/test@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3
        with:
          flavor: ${{ matrix.flavor }}
          type: ${{ matrix.type }}

      - name: Debug Output
        if: ${{ always() }}
        uses: defenseunicorns/uds-common/.github/actions/debug-output@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3

      - name: Save logs
        if: always()
        uses: defenseunicorns/uds-common/.github/actions/save-logs@a99629a47585162e7a133c6f58c9874268103155 # v1.28.3
        with:
          suffix: ${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: always()
        with:
          name: playwright-report-${{ matrix.type }}-${{ matrix.flavor }}-${{ github.run_id }}-${{ github.run_attempt }}
          path: tests/.playwright/reports/
          retention-days: 30
